{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-engine",
    "version": "0.69.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-debug.aar",
          "url": "hermes-engine-0.69.12-debug.aar",
          "size": 3953388,
          "sha512": "6a1dc6c08c8720d976343ea855cbe0239cb8ef0db53fdc0d237ef7e35addee29d349ea09e4097096646cac22cfa5f7678f4dae8f81e469f38db790e2e42e2d1c",
          "sha256": "667091def2720c1248dbd70f19c7865858ff784bf92076c186eb8c1f38d3d9ff",
          "sha1": "e82120e60a45042f2c42f8beb1115f7e9fa6a845",
          "md5": "fbb8dd532fb0347a422751f2e385b306"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.69.12-debug.aar",
          "url": "hermes-engine-0.69.12-debug.aar",
          "size": 3953388,
          "sha512": "6a1dc6c08c8720d976343ea855cbe0239cb8ef0db53fdc0d237ef7e35addee29d349ea09e4097096646cac22cfa5f7678f4dae8f81e469f38db790e2e42e2d1c",
          "sha256": "667091def2720c1248dbd70f19c7865858ff784bf92076c186eb8c1f38d3d9ff",
          "sha1": "e82120e60a45042f2c42f8beb1115f7e9fa6a845",
          "md5": "fbb8dd532fb0347a422751f2e385b306"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-debug-sources.jar",
          "url": "hermes-engine-0.69.12-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "debugVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-debug-javadoc.jar",
          "url": "hermes-engine-0.69.12-debug-javadoc.jar",
          "size": 471534,
          "sha512": "f8a89f5e3460f70b7ad4f6738d1aa708300863edae63f91984b89b1c98fce1bad7262f562c7fd109037bdf75a2e06586763b5f0e9a054e401dde22c3fcba8ea4",
          "sha256": "adeb2433504a61d6b543330bc572e4c4a76ab72ebd117bac0c835145cee60b90",
          "sha1": "e58efaeaafbfaf3645b2f76899034195e59e70eb",
          "md5": "9bcbc62cf79199ee501ef31767406b71"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-release.aar",
          "url": "hermes-engine-0.69.12-release.aar",
          "size": 3499282,
          "sha512": "5fc49b9b5109ff35e4174a9a10c02a21d535e5e93887d6f448c5db0b1148bad8c499843dd8a820b9c54cbc2b3d65ab3e007fe428be533ed393069601a02882f3",
          "sha256": "fb7d420ee39d8218f5b57f0acbd5ad7e315839bb32bf83ca6f3b71c82e9a5608",
          "sha1": "2c45c6b76f1bf5936d01a4b9224ecd1a8cf88739",
          "md5": "274999821b428b14ae97b0b1739ebd71"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.69.12-release.aar",
          "url": "hermes-engine-0.69.12-release.aar",
          "size": 3499282,
          "sha512": "5fc49b9b5109ff35e4174a9a10c02a21d535e5e93887d6f448c5db0b1148bad8c499843dd8a820b9c54cbc2b3d65ab3e007fe428be533ed393069601a02882f3",
          "sha256": "fb7d420ee39d8218f5b57f0acbd5ad7e315839bb32bf83ca6f3b71c82e9a5608",
          "sha1": "2c45c6b76f1bf5936d01a4b9224ecd1a8cf88739",
          "md5": "274999821b428b14ae97b0b1739ebd71"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-release-sources.jar",
          "url": "hermes-engine-0.69.12-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultJavaDocPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.69.12-release-javadoc.jar",
          "url": "hermes-engine-0.69.12-release-javadoc.jar",
          "size": 471381,
          "sha512": "f26c2f30eec2d2f449de6870b89a8869ca84cedbc7d7ef3737034aadfccd66e713236cb03392f0acee246158e6f07bf0b36a67f726f84a2639830a992b93ba3e",
          "sha256": "6bbac5317dcb9446c05728bb40c5af0431174f138486be520ca2bd061190cea3",
          "sha1": "72708a699c4f8813ea578b17459c6aea7d9040e3",
          "md5": "cc0fbd93be90f8b85205ae83599c7709"
        }
      ]
    }
  ]
}
