{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "hermes-engine",
    "version": "0.70.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "debugVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.13-debug.aar",
          "url": "hermes-engine-0.70.13-debug.aar",
          "size": 4031696,
          "sha512": "d7c18b7a225a7c97a3f0c35e3cf6027d8d66a83da377d6d1e8661d75a747b5893777b848cd3b32bbae0de35e8cc1e89d7f2f7eba5d4e1d3048ba2451e7f67ed4",
          "sha256": "1234a4543e85c2221fc88ad75d3536efd42817107a4e3b573ee6e6f737cfbb3b",
          "sha1": "ef1514aa1a60ac0037ca19cd493f3b9305bd7c74",
          "md5": "3a285ee13bda4a6c67d730e98b706291"
        }
      ]
    },
    {
      "name": "debugVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.13-debug.aar",
          "url": "hermes-engine-0.70.13-debug.aar",
          "size": 4031696,
          "sha512": "d7c18b7a225a7c97a3f0c35e3cf6027d8d66a83da377d6d1e8661d75a747b5893777b848cd3b32bbae0de35e8cc1e89d7f2f7eba5d4e1d3048ba2451e7f67ed4",
          "sha256": "1234a4543e85c2221fc88ad75d3536efd42817107a4e3b573ee6e6f737cfbb3b",
          "sha1": "ef1514aa1a60ac0037ca19cd493f3b9305bd7c74",
          "md5": "3a285ee13bda4a6c67d730e98b706291"
        }
      ]
    },
    {
      "name": "debugVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.13-debug-sources.jar",
          "url": "hermes-engine-0.70.13-debug-sources.jar",
          "size": 62707,
          "sha512": "b6d659b87a103dd21026d8715420d047b70e76219d39121795598811cff2c7bb6cf3a860d8836fe6eeb753f785d7c2f7b961ea48c5cba27626a6e1cb5b07ee62",
          "sha256": "1fe6791aeefb0391d319d763c655a6f8232676141b886d0a467b8834a0b86497",
          "sha1": "75340c383a5d55a37d68181f12b1d8d939a3f065",
          "md5": "7b864274b543d21ee7d7c9c8e7f7b043"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultApiPublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.13-release.aar",
          "url": "hermes-engine-0.70.13-release.aar",
          "size": 3456702,
          "sha512": "57b3715e1b3a9d0579a529e73adb458bf93678975c138358c7ec1be4969ebb3e8ebcbe7de82ca362129a3b19767ffe0f65f36e8bdd91ee271a523c0956666b10",
          "sha256": "a306c1fb38724c8cdc1561576b9f5a3cb823751446b01d6064a55a94525acde2",
          "sha1": "a494d94ecfe45b217042b978a6ad2599efa8b62b",
          "md5": "7e2e206c625f4e5d46571423fe7381f5"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultRuntimePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.3"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "hermes-engine-0.70.13-release.aar",
          "url": "hermes-engine-0.70.13-release.aar",
          "size": 3456702,
          "sha512": "57b3715e1b3a9d0579a529e73adb458bf93678975c138358c7ec1be4969ebb3e8ebcbe7de82ca362129a3b19767ffe0f65f36e8bdd91ee271a523c0956666b10",
          "sha256": "a306c1fb38724c8cdc1561576b9f5a3cb823751446b01d6064a55a94525acde2",
          "sha1": "a494d94ecfe45b217042b978a6ad2599efa8b62b",
          "md5": "7e2e206c625f4e5d46571423fe7381f5"
        }
      ]
    },
    {
      "name": "releaseVariantDefaultSourcePublication",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "release",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hermes-engine-0.70.13-release-sources.jar",
          "url": "hermes-engine-0.70.13-release-sources.jar",
          "size": 62694,
          "sha512": "205a0fd395d6d02c27c4611ae1ceca7ccb4f3554f17f44d338f9ffef2e3521e933616e74ac1b17bb7d300891ede5ecf58e966a11becda27f6760f862f2316783",
          "sha256": "e622d9a7db5ba1a2161785ab8745dda58d1012aad04f7f9489fce207cf567f8a",
          "sha1": "34cf662170d553da87ddd8ef2213f13212955d1d",
          "md5": "c8db891c3be1b407d7079c02c303243b"
        }
      ]
    }
  ]
}
