{
  "formatVersion": "1.1",
  "component": {
    "group": "com.facebook.react",
    "module": "react-native",
    "version": "0.67.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.67.5.aar",
          "url": "react-native-0.67.5.aar",
          "size": 17805254,
          "sha512": "c64d42bf1e6cc210b7092151e8b4e54de164378678321528c20598727489255c71c9b5ececf76e5d2bcf28d241f3d65a72bd46abef2408c6091e7a06c2b3a52f",
          "sha256": "04ab3a910f9e48513b99b232ee5a6c0eae4bc529e313d87f7d4dd09c74639b1e",
          "sha1": "334ca9e2426c5d72705382016cf3708980c2a241",
          "md5": "ee834cad55b3aff4200f49f58eab4782"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.facebook.infer.annotation",
          "module": "infer-annotation",
          "version": {
            "requires": "0.18.0"
          }
        },
        {
          "group": "com.facebook.yoga",
          "module": "proguard-annotations",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "androidx.autofill",
          "module": "autofill",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "fresco",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "imagepipeline-okhttp3",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.fresco",
          "module": "ui-common",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.facebook.soloader",
          "module": "soloader",
          "version": {
            "requires": "0.10.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.9.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.facebook.fbjni",
          "module": "fbjni-java-only",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "react-native-0.67.5.aar",
          "url": "react-native-0.67.5.aar",
          "size": 17805254,
          "sha512": "c64d42bf1e6cc210b7092151e8b4e54de164378678321528c20598727489255c71c9b5ececf76e5d2bcf28d241f3d65a72bd46abef2408c6091e7a06c2b3a52f",
          "sha256": "04ab3a910f9e48513b99b232ee5a6c0eae4bc529e313d87f7d4dd09c74639b1e",
          "sha1": "334ca9e2426c5d72705382016cf3708980c2a241",
          "md5": "ee834cad55b3aff4200f49f58eab4782"
        }
      ]
    }
  ]
}
